FROM registry.saas.hand-china.com/tools/mysql:5.6

MAINTAINER CongLei

RUN yum install mysql mysql-server
RUN /etc/init.d/mysqld start &&\

ADD sakila-schema.sql /docker-entrypoint-initdb.d/
ADD sakila-date.sql /docker-entrypoint-initdb.d/